### PR TITLE
add install-deps to readme

### PR DESCRIPTION
**Pull request by hughperkins**
Not sure your preferred solution to this.  Do you want to keep dependencies apart, or combined?  One line or multiple lines?

### CODE REVIEW

**Comment by hughperkins** [comment]
Maybe best to keep apart...

**Comment by hughperkins** [comment]
Repushed to preserve the original readme, just change `ezinstall` to `distro.

**Comment by fmassa** [comment]
@hughperkins maybe just one last change, could you also update the [readme in the main torch webpage](https://github.com/torch/torch.github.io/blob/master/docs/00-getting-started.md)

**Comment by hughperkins** [comment]
Ok. Addressed in https://github.com/torch/torch.github.io/pull/40

**Pull request merged**
