### PR TITLE
Search for nvcc in /usr/local/cuda, if not found in PATH

### PR DESCRIPTION
**Pull request by hughperkins**

### CODE REVIEW

**Comment by soumith** [comment]
Thanks!

**Comment by stas-sl** [comment]
Hi, I'm using zsh 5.2 on OS X and I have the following error:

```
./install.sh: line 65: conditional binary operator expected
./install.sh: line 65: syntax error near `path_to_nvcc'
./install.sh: line 65: `if [[ -v path_to_nvcc ]]; then { # look for it in /usr/local'
```
Looks like -v condition is not recognised by zsh.

**Comment by hughperkins** [comment]
o :-O  That sucks.  Searching a bit.  Seems like maybe something like:
```
#!/bin/bash

set -e
set -x

if [ -z ${foo+yes} ]; then {
  echo not defined
} else {
  echo defined
} fi
```
coudl be the correct way (reference http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash/13864829#13864829 and also http://unix.stackexchange.com/questions/56837/how-to-test-if-a-variable-is-defined-at-all-in-bash-prior-to-version-4-2-with-th/56846#56846 )

**Comment by hughperkins** [comment]
Interestignly, it's complicated slightly, because zsh doesnt return nothing for which, if not found:
```
% which nvcc
nvcc not found
```

**Comment by hughperkins** [comment]
Seems like maybe simply testing `$?` is or isnt 0 could be sufficient?  in bash:
```
ubuntu@peach:~/git/distro$ a=$(which nvcc)
ubuntu@peach:~/git/distro$ echo $?
1
ubuntu@peach:~/git/distro$ a=$(which gcc)
ubuntu@peach:~/git/distro$ echo $?
0
```
In zsh:
```
ubuntu@peach ~/git/distro % a=$(which nvcc)
ubuntu@peach ~/git/distro % echo $?
1
ubuntu@peach ~/git/distro % a=$(which gcc) 
ubuntu@peach ~/git/distro % echo $?       
0
```

**Pull request merged**
