### PR TITLE
fail on error; show commands; CUDA optional; ipython failure non-fatal

### PR DESCRIPTION
**Pull request by hughperkins**
- fail on error (`set -e`)
- show commands  (`set -x`)
- CUDA optional  (`NOCUDA=1 ./install.sh`)
- ipython failure non-fatal  (surrounded by `set +e`, `set -e`)

### CODE REVIEW

**Comment by hughperkins** [comment]
Added commit that creates ~/torch/activate.  For now, old message continues to exist.

**Comment by soumith** [comment]
I am still on the wall on this one. I think what we can do is move around the package installs such that the "core necessary packages" have a "set -e", and that is switched off after they get installed.

**Comment by soumith** [comment]
the problem i foresee is that this is going to have a few packages like qt/qlua fail on more machines than we can think of...

**Comment by hughperkins** [comment]
Well... maybe putting set -e around core packages for now could be a good compromise?  Gradually can expand the proportion of lines that can go inside the set -e, over several months perhaps?

**Comment by hughperkins** [comment]
Ah, you're saying, set -e is too violent, means that it will fail on machines where otherwise would install kind-of ok, enough for someone to use?

**Comment by soumith** [comment]
i'm sorry, i'll get to this after friday. have this conference deadline, so haven't had the time.

**Comment by hughperkins** [comment]
Ah, ok :-)

**Pull request closed without merging**
