### PR TITLE
add install-deps, from ezinstall

### PR DESCRIPTION
**Pull request by hughperkins**
since this messes with `blame`, I'm not submititng this because I think you should accept it.  It's mostly to show willing really.

### CODE REVIEW

**Comment by hughperkins** [comment]
Thanks! :-)

**Comment by deltheil** [comment]
The README should be updated too, right? (with `curl -s https://raw.githubusercontent.com/torch/distro/master/install-deps | bash`)

**Comment by hughperkins** [comment]
Yes, I was pondering that...

**Comment by hughperkins** [comment]
Created draft PR for readme update at https://github.com/torch/distro/pull/75

**Pull request merged**
